
from scrapy.item import Item, Field

class BpPropertyItem(Item):
    # define the fields for your item here like:
    price = Field()
    location = Field()
    num_bed_rooms = Field()
    num_bath_rooms = Field()
    area = Field()
    building_type = Field()
    purpose = Field()
    amenities = Field()
    property_url= Field()

class PBazarItem(Item):

    property_type = Field()
    price_per_month = Field()
    price_per_sft = Field()
    price = Field()
    location = Field()
    area_sft = Field()
    attach_bathrooms = Field()
    common_bathrooms = Field()
    bedrooms = Field()
    floor = Field()
    floor_type = Field()
    parking_space = Field()
    balcony = Field()
    dining = Field()
    living = Field()
    total_floor = Field()
    size_in_katha = Field()
    view = Field()
    road_width = Field()
    land_katha = Field()
    garage_number = Field()

class ashSpiderItem(Item):
    # define the fields for your item here like:
    location = Field()
    price = Field()
    bedrooms = Field()
    bathrooms = Field()
    area = Field()
    ptype = Field()
    pstatus = Field()
    garage = Field()
    url = Field()
    amenities = Field()
    
    
    class RentalHomeBD(Item):
    # define the fields for your item here like:
    basic_info = Field()
    amenities = Field()
    address = Field()
    type = Field()
    title = Field()
    price_in_BDT = Field()
    details = Field()
    purpose = Field()
    page_url = Field()
    listing_url = Field()

class iqibdPropsItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    property_link = scrapy.Field()
    price = scrapy.Field()
    location = scrapy.Field()
    num_bed_rooms = scrapy.Field()
    num_bath_rooms = scrapy.Field()
    area = scrapy.Field()
    building_type = scrapy.Field()
    floor=scrapy.Field()
    land_size=scrapy.Field()
    garage = scrapy.Field()
    year_built= scrapy.Field()
    status = scrapy.Field()
    num_balcony = scrapy.Field()
    interior = scrapy.Field()
    unit = scrapy.Field()
    wifi = scrapy.Field()
    parking = scrapy.Field()
    security = scrapy.Field()
    elevator = scrapy.Field()
    emergency_stairs = scrapy.Field()
    generator = scrapy.Field()
    tv_cable = scrapy.Field()
    government_gas = scrapy.Field()
    cctv= scrapy.Field()
    reception= scrapy.Field()
    swimming_pool= scrapy.Field()
    balcony = scrapy.Field()
    garden = scrapy.Field()
    fitness_center=scrapy.Field()
    air_conditioning=scrapy.Field()
    central_heating = scrapy.Field()
    pets_allow = scrapy.Field()
    servant_room = scrapy.Field()